### ISSUE TITLE
Iris 2.0 import error on Mac

### ISSUE THREAD

**Issue by Marston** [giancosta86/Iris#1]
Hi,

I installed iris 2.0 in a python 3.6 environment on my Mac using pip.
But when I try to load iris objects such as analysis, I get an error. Iris 2.0 installed ok and it imports, but there are no objects associated with it:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-980e9c3d557a> in <module>()
      1 import iris
----> 2 import iris.analysis.cartography
      3 import iris.plot as iplt
      4 import iris.quickplot as qplt

ModuleNotFoundError: No module named 'iris.analysis'

In [2]: from iris import *

In [3]: whos
Variable   Type      Data/Info
------------------------------
iris       module    <module 'iris' from '/opt<...>ckages/iris/__init__.py'>

In [6]: dirs(iris)
Out[6]: []

```
any idea what's going on and how to fix it? I've already tried reinstalling Iris, but this didn't help.

**Comment by giancosta86** [comment]
There is probably a conflict with another project named Iris... :( If you have a look at [the source code](https://github.com/giancosta86/Iris/tree/master/iris) of my project, there is no module named **iris.analysis.cartography**, or **iris.plot**, ....

**Comment by Marston** [comment]
Aha...my bad.
You are not: http://scitools.org.uk/iris. 
Sorry :-(

**Comment by giancosta86** [comment]
No problem! ^___^ Anyway, feel free to use my Iris as well, should you need it! ^__^!
