### ISSUE TITLE
Namespace collision - Iris

### ISSUE THREAD

**Issue by pelson** [giancosta86/Iris#2]
Hi @giancosta86,

I'm writing to you as it appears that there is a naming collision between this package and a package I [work on (SciTools/Iris)](https://github.com/SciTools/iris/).

In general, namespace collisions will inevitably occur in Python (some mitigations were attempted at http://legacy.python.org/dev/peps/pep-0423, but still, they will always happen).

Fortunately the communities we target are sufficiently different that it is unlikely users will want to install both iris' in the same environment, and that any confusion should be *reasonably* quick to identify. That said, [an issue cropped up a little while ago](https://github.com/giancosta86/Iris/issues/1) where the confusion apparently wasn't obvious to the user (*and* they managed to find this repo to raise an issue).

Slightly more frustratingly, pip gives us no way to disambiguate to our users when they ```pip install iris```. It would be great if it asked the user:

```
Do you mean?:
(1) A general-purpose library for Python [iris]
(2) A powerful, easy to use, and community-driven Python library for
    analysing and visualising meteorological and oceanographic data sets [scitools-iris]
```

Alas, pip doesn't currently support this functionality, so I thought I'd just get in touch to see if the iris name is still being actively used by you on pypi? And if not, whether you'd consider transferring it to the scitools/iris project? Naturally, there is absolutely no obligation on your behalf - ultimately the ```iris``` name was registered on pypi by you perfectly legitimately, but I just wanted to raise the question. No hard feeling if not. 😄 

Appreciate your time,

Best,

Phil (@pelson)

**Comment by pelson** [comment]
Just a friendly bump in case this got lost in your inbox.

Cheers,

**Comment by giancosta86** [comment]
Thank you for your suggestion.

Please, refer to: https://github.com/giancosta86/Iris/releases/tag/v3.1
